### ISSUE TITLE
Coffeescript variables not recognized in template

### ISSUE THREAD

**Issue by xoumi** [kaisermann/svelte-preprocess#134]
**Describe the bug**
 Variables defined in coffeescript are not recognized by markup, be it inside template tag or not.

**Logs**
```
'nums' is not defined (10:7)
 8:
 9:
10: {#each nums as num}
```
**To Reproduce**
```html
<script lang="coffee">
nums = [1, 2, 3]
</script>

<template>
{#each nums as num}
  <div> {num} </div>
{/each}
</template>
```

I'm using the Sapper Webpack template for the example

**Stacktraces**
<details>
  <summary>This is what shows up in the browser</summary>
500
nums is not defined
ReferenceError: nums is not defined
    at eval (webpack:///./src/routes/index.svelte?:12:73)
    at Object.$$render (webpack:///./node_modules/svelte/internal/index.mjs?:1427:22)
    at Object.default (webpack:///./src/node_modules/@sapper/internal/App.svelte?:36:190)
    at eval (webpack:///./src/routes/_layout.svelte?:16:224)
    at Object.$$render (webpack:///./node_modules/svelte/internal/index.mjs?:1427:22)
    at eval (webpack:///./src/node_modules/@sapper/internal/App.svelte?:33:151)
    at $$render (webpack:///./node_modules/svelte/internal/index.mjs?:1427:22)
    at Object.render (webpack:///./node_modules/svelte/internal/index.mjs?:1435:26)
    at handle_page (webpack:///./src/node_modules/@sapper/server.mjs?:2495:93)
</details>

**Information about your project:**

- Your browser and the version: Occuring on both Chrome and Firefox
- Your operating system: Win10
- `svelte-preprocess` version: 3.7.1

- Whether your project uses Webpack or Rollup: Webpack

**Additional context**
The content in the script tag gets converted to:
```js
var nums;
nums = [1, 2, 3];
````
If I replace the coffeescript with the above and remove the lang attribute it works as expected though.

**Comment by kaisermann** [comment]
Hey @xoumi :wave: Thanks for the detailed issue. It seems that whenever a coffeescript code doesn't have an `import`/`export`, the compiler wraps the code with an IIFE. By passing the `bare: true` option to the compiler (see it here: https://coffeescript.org/#lexical-scope), this behavior stops and svelte will be able to find your variables again. I've just released version `3.7.2` which sets it to `true` as the default behavior.

**Comment by rhysallister** [comment]
> Hey @xoumi wave Thanks for the detailed issue. It seems that whenever a coffeescript code doesn't have an `import`/`export`, the compiler wraps the code with an IIFE. By passing the `bare: true` option to the compiler (see it here: https://coffeescript.org/#lexical-scope), this behavior stops and svelte will be able to find your variables again. I've just released version `3.7.2` which sets it to `true` as the default behavior.

7d38bfd doesn't fix #134.  `bare: false` is passed to the compiler in [src/transformers/coffeescript.ts](https://github.com/sveltejs/svelte-preprocess/commit/7d38bfde34b6fafeca7e8df490348fd2004cdb1a#diff-e8b26062474af7d74da2ba7ce7717bdb)

[See comment here](https://github.com/sveltejs/svelte-preprocess/commit/7d38bfde34b6fafeca7e8df490348fd2004cdb1a#commitcomment-40380138)
